kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusternet:agent:admin
  namespace: clusternet-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusternet:agent:admin
  namespace: clusternet-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clusternet:agent:admin
subjects:
  - kind: ServiceAccount
    name: clusternet-agent
    namespace: clusternet-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusternet:app:deployer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusternet:app:deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusternet:app:deployer
subjects:
  - kind: ServiceAccount
    name: clusternet-app-deployer
    namespace: clusternet-system
  - kind: ServiceAccount
    name: clusternet-agent
    namespace: clusternet-system
